name: 'Run eclint with reviewdog'
description: '🐶 Run eclint with reviewdog on pull requests to improve code review experience.'
author: 'Felix Bartels'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review,github-check].
      Default is github-pr-check.
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    default: 'github-pr-check'
  path:
    description: "Base directory to run eclint."
    default: '.'
  exclude:
    description: "Exclude patterns of target files. Same as `--exclude-dir` of `grep` command."
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'zoom-in'
  color: 'purple'
